### ISSUE TITLE
Question about concurrency

### ISSUE THREAD

**Issue by troex** [djreimer/mini_cache#2]
Hi, it's more a question rather then an issue, I'm running puma server with 200+ threads, every thread usually is hit by 70-200 requests per seconds. I need to implement minimal caching for very small amount of data. If I put mini_cache code inside main puma worker I think it will work but how to deal with concurrency if key is expired and accessed thousands of times per second it will probably raise race condition. Do you have any suggestions on how to avoid that?

**Comment by derrickreimer** [comment]
Good question. This implementation uses a Ruby `Hash` to store data, which is not thread-safe. I'd be open to a PR that uses a thread-safe hash implementation under the covers, but my recommendation would be to use a true cache store (like memcached or redis) if you need concurrent access.

Hope this helps!
